### ISSUE TITLE
SSL error on Python SDK calls

### ISSUE THREAD

**Issue by hermanocabral** [Semantria/semantria-sdk#16]
Hello,

The Semantria API calls made by the Python SDK are failing with the "CERTIFICATE_VERIFY_FAILED" error when using Python 2.7.9+. Apparently the issue can be traced to PEP 0476: Enabling certificate verification by default for stdlib http clients.

I've tried upgrading my root certificates, using the latest versions of OpenSSL, pyOpenSSL and so on, nothing helped.

Have you seen this issue before?

Thanks.

More details on the issue can be found here: 
* http://bugs.python.org/issue23052
* https://www.python.org/dev/peps/pep-0476/

**Comment by george-kozlov** [comment]
Hello,

Can you please confirm what API URL you use?
We have staging environment with self-signing certificate, maybe your code refers to it...

--
Regards,
George
