### ISSUE TITLE
is there a way to send a url to extract information instead of document?

### ISSUE THREAD

**Issue by streamgao** [Semantria/semantria-sdk#17]
is there a way to send a url to extract information instead of document?
Your online demo just require send a link and then get the main text for that link.  hope it is included in the sdk as well. 
Other, do you mind share something on extracting the main text from a link?

Thank you

**Comment by streamgao** [comment]
never mind, i found some solutions.

**Comment by george-kozlov** [comment]
Hello,

Semantria doesn't support direct analysis of URLs, just actual verbatim.
Customers are not interested in that feature so we don't add it to the API.
Web demo is using 3rd party service for URLs crawling, like Diffbot.

--
Regards,
George

**Comment by streamgao** [comment]
okay I know ,

Thank you!



XI GAO
gaoxi1992@hotmail.com<mailto:gaoxi1992@hotmail.com>



Stream Gao
gaoxi1992@hotmail.com<mailto:gaoxi1992@hotmail.com>

Master Candidate
ITP NYU
http://www.streamgao.com






On Apr 25, 2016, at 06:33, George <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

Semantria doesn't support direct analysis of URLs, just actual verbatim.
Customers are not interested in that feature so we don't add it to the API.
Web demo is using 3rd party service for URLs crawling, like Diffbot.

Regards,
George
