### ISSUE TITLE
cannot import semantria

### ISSUE THREAD

**Issue by streamgao** [Semantria/semantria-sdk#18]
I got the problem for just importing semantria:
import semantria, time, uuid

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.6-intel/egg/semantria/__init__.py", line 3, in <module>
    
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/semantria_sdk-4.1.85-py2.7.egg/semantria/session.py", line 453
    raise SemantriaError('Parameter not found: %s' % doc_id).
                                                            ^
SyntaxError: invalid syntax

Already installed:

pip install semantria_sdk
Requirement already satisfied (use --upgrade to upgrade): semantria-sdk in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/semantria_sdk-4.1.85-py2.7.egg

my python and pip:
172-16-245-216:crawler stream$ which python
/Library/Frameworks/Python.framework/Versions/2.7/bin/python
172-16-245-216:crawler stream$ which pip
/Library/Frameworks/Python.framework/Versions/2.7/bin/pip

**Comment by streamgao** [comment]
Problem solved:
download package.  open file semantria/session.py
line 453
change "SemantriaError('Parameter not found: %s' % doc_id)."
to "SemantriaError('Parameter not found: %s' % doc_id)"
(remove the last letter)

python setup.py install

**Comment by george-kozlov** [comment]
Thanks for letting us know!
I've just fixed the typo and updated repository.

--

Regards,
George Kozlov  Senior Cloud Architect

Lexalytics  Read Between The Lines™

<http://bd.semantria.com/a7f5c9324d3f737a5c>www.lexalytics.com<http://www.lexalytics.com/>


This message (including any attachments) may contain confidential information intended for a specific individual and purpose, and is protected by law. If you are not the intended recipient, you should delete this message and contact the sender.

**Comment by jcoriat** [comment]
You probably want to push it to the version being distributed on your website... Because as a new prospect I had to scratch my head for quite a while before ending up on this page :)
