### ISSUE TITLE
httplib.HTTPException: (413, 'Request Entity Too Large')

### ISSUE THREAD

**Issue by streamgao** [Semantria/semantria-sdk#19]
Im testing python API now and got 412 error.
Traceback (most recent call last):
  File "keywordsextraction.py", line 133, in <module>
    extractinfoAslist([nytpage.contentpall])
  File "keywordsextraction.py", line 59, in extractinfoAslist
    status = session.queueCollection({"id": collection_id, "documents": textlist})
  File "build/bdist.macosx-10.6-intel/egg/semantria/session.py", line 504, in queueCollection
  File "build/bdist.macosx-10.6-intel/egg/semantria/session.py", line 643, in _runRequest
  File "build/bdist.macosx-10.6-intel/egg/semantria/session.py", line 649, in _resolveError

httplib.HTTPException: (413, 'Request Entity Too Large')

I use the exact amount of same text in the online demo and that’s totally fine. the # of words actually even smaller than the source.txt in the example folder.

Is there anyway to sole the problem?

**Comment by george-kozlov** [comment]
Hello,

Are you sending a single document or a batch of documents?
413 HTTP status means that you exceeded the limit of maximum allowed document size.
By default we limit the documents to 8192 characters. Have you sent larger document (more than 8KB)?

--

Regards,
George Kozlov  Senior Cloud Architect

Lexalytics  Read Between The Lines™

<http://bd.semantria.com/a7f5c9324d3f737a5c>www.lexalytics.com<http://www.lexalytics.com/>


This message (including any attachments) may contain confidential information intended for a specific individual and purpose, and is protected by law. If you are not the intended recipient, you should delete this message and contact the sender.
