### ISSUE TITLE
com.semantria.mapping.output.Opinion is deserialized from json with null fields

### ISSUE THREAD

**Issue by Cristi003** [Semantria/semantria-sdk#4]
Gson typeadapter uses private fields name for mapping java fields to json object keys. Since private fields in Opinion class are prefixed with ````m_```` compared with the json object keys, the mapping is incorrect.

**Comment by george-kozlov** [comment]
Hi Cristi,

Thanks for your feedback. We already addressed this issue in our private repository.
I will push update to Github soon.

--
Regards,
George
